---
title: "Statistics 243: Introduction to Statistical Computing"
subtitle: "UC Berkeley, Spring 2024"
listing:
  - id: buttons
    template: assets/buttons.ejs
    contents: buttons.yml
---

::: {#buttons}
:::

## Course materials

See the links above for the key resources for the course.

Most course content (in particular unit notes, labs, and problem sets) are available through this website via the links in the left sidebar.

## Questions about taking the class

If you would like to audit the class, enroll as a UC Berkeley undergraduate, or enroll as a concurrent enrollment student (i.e., for visiting students), or for some other reason are not enrolled, please fill out [this survey](https://forms.gle/TBD) as soon as possible. All those enrolled or wishing to take the class should have filled it out by Friday August 30 at noon.

Undergraduates can only take the course with my permission and once all graduate students have an opportunity to register. I do not know if there will be space, but I recommend you attend the course as if you were enrolled until this is clear.

Concurrent enrollment students (e.g., exchange students from other universities/countries) can take the course with my permission and once all UC Berkeley students have had an opportunity to register. I do not know if there will be space, but I recommend you attend the course as if you were enrolled until this is clear.

Please see the syllabus for the math and statistics background I expect, as well as the need to be familiar with Python or to get up to speed in Python during the first few weeks of the semester.

The first three weeks involve a lot of moving pieces, in part related to trying to get everyone up to speed with the bash shell and Python. Please use [the schedule](schedule.qmd) to keep on top of what you need to do.

